[project]
name = "stackable"
description = "Stackable - Launch & Trade Vibe Tokens with AI on Stacks"
authors = ["Stackable Team"]
telemetry = true
cache_dir = ".cache"
requirements = []
[contracts.sip010-token-trait]
path = "contracts/sip010-token-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.prompt-token]
path = "contracts/prompt-token.clar"
clarity_version = 2
epoch = 2.5

[contracts.bonding-curve]
path = "contracts/bonding-curve.clar"
clarity_version = 2
epoch = 2.5

[contracts.xp-system]
path = "contracts/xp-system.clar"
clarity_version = 2
epoch = 2.5

[contracts.marketplace]
path = "contracts/marketplace.clar"
clarity_version = 2
epoch = 2.5

[contracts.governance]
path = "contracts/governance.clar"
clarity_version = 2
epoch = 2.5

[repl]
costs_version = 3
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[[repl.analysis.check_checker.passes]]
pass = "check_checker"
